name: MoreLoomLayers
version: '1.10'
main: me.bear.moreLoomLayers.MoreLoomLayers
api-version: '1.20'
authors: [ "Bearofbusiness" ]
commands:
  showbannerlayers:
    description: Shows the layers of a banner
    aliases: [sbl]